permalink: /:year/:month/:day/:title 
url: http://istlab.dmst.aueb.gr/~george/blog
baseurl: blog
paginate: 5
future: false
pygments: true
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

#Author
author:
  name: Georgios Gousios
  email: gousiosg@gmail.com

# For google analytics
tracking_id : 'UA-123-12'

# Discus comments
comments: gousiosg

# Some custom pages
archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html

